name: XcodeMCPSwiftApp

options:
  bundleIdPrefix: com.xcodemcpswiftapp
  deploymentTarget:
    macOS: "14.0"
  createIntermediateGroups: true
  groupSortPosition: top
  xcodeVersion: "16.0"

packages:
  XcodeMCPBridge:
    url: https://github.com/renderplace/XcodeMCPBridge.git
    from: "1.0.0"

targets:
  XcodeMCPSwiftApp:
    type: application
    platform: macOS
    sources:
      - path: Sources/XcodeMCPSwiftApp
    dependencies:
      - package: XcodeMCPBridge
        product: XcodeMCPBridge
      - package: XcodeMCPBridge
        product: mcpbridge-cli
        embed: false
        link: false
    postCompileScripts:
      - script: |
          mkdir -p "${BUILT_PRODUCTS_DIR}/${PRODUCT_NAME}.app/Contents/Resources"
          cp "${BUILT_PRODUCTS_DIR}/mcpbridge-cli" "${BUILT_PRODUCTS_DIR}/${PRODUCT_NAME}.app/Contents/Resources/mcpbridge-cli"
          chmod 755 "${BUILT_PRODUCTS_DIR}/${PRODUCT_NAME}.app/Contents/Resources/mcpbridge-cli"
        name: Embed MCPBridgeCLI
        inputFiles:
          - $(BUILT_PRODUCTS_DIR)/mcpbridge-cli
        outputFiles:
          - $(BUILT_PRODUCTS_DIR)/$(PRODUCT_NAME).app/Contents/Resources/mcpbridge-cli
    settings:
      base:
        PRODUCT_BUNDLE_IDENTIFIER: com.xcodemcpswiftapp.app
        PRODUCT_NAME: "Xcode MCP Swift App"
        MARKETING_VERSION: "1.0.0"
        CURRENT_PROJECT_VERSION: 1
        GENERATE_INFOPLIST_FILE: YES
        INFOPLIST_KEY_LSApplicationCategoryType: "public.app-category.developer-tools"
        INFOPLIST_KEY_NSHumanReadableCopyright: "Copyright © 2026 Anton Gregorn. All rights reserved."
        MACOSX_DEPLOYMENT_TARGET: "14.0"
        SWIFT_VERSION: "5.9"
        CODE_SIGN_STYLE: Automatic
        ENABLE_APP_SANDBOX: NO
